FROM golang:1.22-alpine AS build

WORKDIR /app
COPY gateway/go.mod ./
COPY gateway/cmd ./cmd
COPY gateway/internal ./internal
RUN go build -o gateway ./cmd/server

FROM alpine:3.20

WORKDIR /app
COPY --from=build /app/gateway ./gateway
EXPOSE 8080
CMD ["./gateway"]
